// <auto-generated />
using System;
using CookiFind.Application.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CookiFind.Application.Migrations
{
    [DbContext(typeof(CookiFindDbContext))]
    partial class CookiFindDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CookiFind.Application.Models.Recipes.Recipe", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid");

                    b.Property<string>("CookidooId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("NutritionInfoId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("NutritionInfoId");

                    b.ToTable("Recipes");
                });

            modelBuilder.Entity("CookiFind.Application.Models.Recipes.RecipeCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CookidooId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("RecipeCategories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("fd0758a6-a1ed-4d05-afdc-d6e4189c7f21"),
                            CookidooId = "VrkNavCategory-RPF-001",
                            Name = "Appetizers"
                        },
                        new
                        {
                            Id = new Guid("03d7257b-cee0-4256-8e43-aac489787fc8"),
                            CookidooId = "VrkNavCategory-RPF-002",
                            Name = "Soups"
                        },
                        new
                        {
                            Id = new Guid("dacbb358-6082-4a10-a210-9a459077f0d5"),
                            CookidooId = "VrkNavCategory-RPF-003",
                            Name = "Pasta & Rice Dishes"
                        },
                        new
                        {
                            Id = new Guid("fb487a86-7f4b-4536-954b-b5616e8dd821"),
                            CookidooId = "VrkNavCategory-RPF-004",
                            Name = "Main dishes – Meat"
                        },
                        new
                        {
                            Id = new Guid("de6b17c6-463a-49e6-9dc1-f0dc42507c6d"),
                            CookidooId = "VrkNavCategory-RPF-005",
                            Name = "Main dishes – Fish"
                        },
                        new
                        {
                            Id = new Guid("12942154-0672-4e48-9789-ed5daf656a0f"),
                            CookidooId = "VrkNavCategory-RPF-006",
                            Name = "Main dishes – Vegetarian"
                        },
                        new
                        {
                            Id = new Guid("f8eff110-05ee-4b94-96f3-55d934e4521a"),
                            CookidooId = "VrkNavCategory-RPF-007",
                            Name = "Main dishes – Other"
                        },
                        new
                        {
                            Id = new Guid("5c818977-76b8-4014-a513-26a64d207d06"),
                            CookidooId = "VrkNavCategory-RPF-008",
                            Name = "Side Dishes"
                        },
                        new
                        {
                            Id = new Guid("39de8ea0-b0d8-4c66-8516-e1c55ee6a6bb"),
                            CookidooId = "VrkNavCategory-RPF-009",
                            Name = "Sauces, Dips and Spreads – Sweet"
                        },
                        new
                        {
                            Id = new Guid("66b44fe0-2a7a-448c-a75f-0882754030d9"),
                            CookidooId = "VrkNavCategory-RPF-011",
                            Name = "Desserts and Sweets"
                        },
                        new
                        {
                            Id = new Guid("4e6c95d6-849e-4e0e-8a37-c93af32ed540"),
                            CookidooId = "VrkNavCategory-RPF-012",
                            Name = "Baking – Savory"
                        },
                        new
                        {
                            Id = new Guid("f7278ad5-3d3c-4912-b42d-92487e1fbbe9"),
                            CookidooId = "VrkNavCategory-RPF-013",
                            Name = "Baking – Sweet"
                        },
                        new
                        {
                            Id = new Guid("21b494af-71fd-4da8-a42c-921e94453b95"),
                            CookidooId = "VrkNavCategory-RPF-014",
                            Name = "Breads and Rolls"
                        },
                        new
                        {
                            Id = new Guid("8a3e3682-a69c-4f58-bcca-94ff48de8b5f"),
                            CookidooId = "VrkNavCategory-RPF-015",
                            Name = "Drinks"
                        },
                        new
                        {
                            Id = new Guid("c93a8d27-d348-4eae-a989-067aca6fc869"),
                            CookidooId = "VrkNavCategory-RPF-016",
                            Name = "Basics"
                        },
                        new
                        {
                            Id = new Guid("b4761e36-4e96-43ae-802e-53595420a52b"),
                            CookidooId = "VrkNavCategory-RPF-017",
                            Name = "Baby food"
                        },
                        new
                        {
                            Id = new Guid("73dd6368-5c3f-4840-aa67-7ecb4bb5aaa9"),
                            CookidooId = "VrkNavCategory-RPF-018",
                            Name = "Sauces, Dips and Spreads – Savory"
                        },
                        new
                        {
                            Id = new Guid("91957ae5-bf50-4d48-9839-d284ea778c26"),
                            CookidooId = "VrkNavCategory-RPF-019",
                            Name = "Breakfast"
                        },
                        new
                        {
                            Id = new Guid("af15b6fc-03d1-4c90-bc86-37bb1fdd1ed8"),
                            CookidooId = "VrkNavCategory-RPF-020",
                            Name = "Snacks"
                        },
                        new
                        {
                            Id = new Guid("2c6e2238-4fb0-4eb7-913f-7571351e1a7f"),
                            CookidooId = "VrkNavigationCategory-rpf-000001303095",
                            Name = "Menus and More"
                        });
                });

            modelBuilder.Entity("CookiFind.Application.Models.Recipes.RecipeNutritionInfo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("CaloriesInKcal")
                        .HasColumnType("double precision");

                    b.Property<double>("CarbohydratesInGrams")
                        .HasColumnType("double precision");

                    b.Property<double>("FatInGrams")
                        .HasColumnType("double precision");

                    b.Property<double>("ProteinInGrams")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("RecipeNutritionInfo");
                });

            modelBuilder.Entity("CookiFind.Application.Models.Recipes.Recipe", b =>
                {
                    b.HasOne("CookiFind.Application.Models.Recipes.RecipeCategory", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CookiFind.Application.Models.Recipes.RecipeNutritionInfo", "NutritionInfo")
                        .WithMany()
                        .HasForeignKey("NutritionInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("NutritionInfo");
                });
#pragma warning restore 612, 618
        }
    }
}
