# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

services:

  db:
      image: postgres:latest
      container_name: cookifind-db
      restart: always
      environment:
        POSTGRES_USER: admin
        POSTGRES_PASSWORD: admin
        POSTGRES_DB: CookiFindDB
      ports:
        - "5432:5432"
      volumes:
        - db_data:/var/lib/postgresql/data

  cookifind.api:
    image: cookifindapi
    container_name: cookifind-api
    build:
      context: .
      dockerfile: CookiFind.Api/Dockerfile
      args:
        - configuration=Debug
    ports:
      - 5034:5034
    depends_on:
      - db
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - Database__ConnectionString=Host=db;Port=5432;Database=CookiFindDB;Username=admin;Password=admin
    volumes:
      - ~/.vsdbg:/remote_debugger:rw

volumes:
  db_data:
