FROM mcr.microsoft.com/dotnet/aspnet:9.0 AS base
WORKDIR /app
EXPOSE 5034

ENV ASPNETCORE_URLS=http://+:5034

USER app
FROM --platform=$BUILDPLATFORM mcr.microsoft.com/dotnet/sdk:9.0 AS build
ARG configuration=Release
WORKDIR /src
COPY ["CookiFind.Api/CookiFind.Api.csproj", "CookiFind.Api/"]
RUN dotnet restore "CookiFind.Api/CookiFind.Api.csproj"
COPY . .
WORKDIR "/src/CookiFind.Api"
RUN dotnet build "CookiFind.Api.csproj" -c $configuration -o /app/build

FROM build AS publish
ARG configuration=Release
RUN dotnet publish "CookiFind.Api.csproj" -c $configuration -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "CookiFind.Api.dll"]
